# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: glove80_lh
    cmake-args: -DZEPHYR_SCA_VARIANT=dtdoctor
  # - board: glove80_rh
  #   cmake-args: -DZEPHYR_SCA_VARIANT=dtdoctor

  # - board: eyelash_corne_right
  #   shield: nice_view

  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: eyelash-corne-studio-left
    
  # - board: eyelash_corne_left
  #   shield: settings_reset
  #   artifact-name: eyelash-corne-settings-reset

  # - board: seeeduino_xiao_ble
  #   shield: totem_dongle dongle_screen
  #   cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
  #   snippet: zmk-usb-logging
  #   artifact-name: totem-dongle-screen

  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  #   artifact-name: totem-settings-reset

  # - board: seeeduino_xiao_ble
  #   shield: totem_left
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #   artifact-name: totem-dongle-left

  # - board: seeeduino_xiao_ble
  #   shield: totem_right
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #   artifact-name: totem-dongle-right
 
  # - board: seeeduino_xiao_ble
  #   shield: totem_left
  #   artifact-name: totem-left

  # - board: seeeduino_xiao_ble
  #   shield: totem_right
  #   artifact-name: totem-right
 